name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1- سحب الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 2- تثبيت Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3- تثبيت المكتبات
      - name: Install deps
        run: npm install

      # 4- عمل Build
      - name: Build project
        run: npm run build

      # 5- الرفع للسيرفر (التعديل الجذري هنا)
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "18.216.109.78"
          REMOTE_USER: "ec2-user"
          SOURCE: "dist/"
          TARGET: "/var/www/FRONTEND"
          ARGS: "-rltgoDzvO --delete"
