name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1- سحب السورس
      - name: Checkout code
        uses: actions/checkout@v3

      # 2- تثبيت Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3- تثبيت البكجات
      - name: Install deps
        run: npm install

      # 4- Build للفرونت
      - name: Build project
        run: npm run build

      # 5- رفع الملفات للسيرفر
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v5
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: "18.216.109.78"
          remote_user: "ec2-user"
          remote_port: 22
          source: "dist/"  # تأكد إن الفولدر اللي بيطلع بعد الـ build اسمه dist وليس build
          target: "/var/www/FRONTEND"
          args: "-rltgoDzvO --delete"
